from dataclasses import dataclass, field
from typing import Optional, Literal

from .langevin import (
    LangevinAdamConfig,
    MultiStartAdamConfig,
)

"Config for feasibility integration"
@dataclass
class FeasibilityConfig:
    """Attributes:
        enabled: Whether to use the learned feasibility penalty.
        checkpoint_path: Path to the trained feasibility model checkpoint.
        lambda_feasibility: Weight of the feasibility penalty in the planner objective.
        noise_level: Sigma value used when scoring candidates with the feasibility model.
        reduction: Batch/trajectory reduction mode for feasibility energy.
        latent_reduction: How to reduce predicted noise over latent dimensions, if supported?
        detach_model: If True, prevents gradients from flowing through the feasibility model.
            Usually keep this False if you want the feasibility penalty to guide optimization.
    """

    enabled: bool = True 
    checkpoint_path: Optional[str] = None
    lambda_feasibility: float = 1.0 # start from raw logs, <1, decrease feasibility influence. >1 increase feasibility influece
    noise_level: float = 0.2 # best out of testing?? 
    reduction: str = "mean"
    latent_reduction: str = "mean"
    detach_model: bool = False

    lambda_transition: float = 0.0 # weight for action-conditioned transition penalty inside feasibility model.
    lambda_action_consistency: float = 0.0 # Optional weight for action-consistency term inside feasibility model. 0 disables it.
    action_consistency_margin: float = 0.1 # Margin for action-consistency term if enabled.

    # NEW: Contrastive learning
    lambda_contrastive_train: float = 0.0  # 0 = disabled, >0 = weight in training
    lambda_contrastive_plan: float = 0.0   # 0 = disabled, >0 = weight at planning time
    contrastive_dim: int = 128

@dataclass
class ALMConfig:
    inner_steps: int = 25
    outer_steps: int = 1 #25
    learning_rate: float = 3e-2
    rho_init: float = 1.0
    rho_growth: float = 1.9
    rho_max: float = 1_000.0
    lambda_video: float = 1.0
    lambda_goal: float = 10.0
    lambda_action: float = 0.005 #0.05
    lambda_action_prior: float = 0.0
    clip_grad_norm: Optional[float] = None
    use_video_init: bool = True
    use_video_loss: bool = True
    fix_states_to_video: bool = False # True to disable optimization of latent states for feasibility 
    use_action_reparameterization: bool = True
    adam_eps: float = 1e-8
    diagnostic_inner_interval: Optional[int] = None
    diagnostic_outer: bool = False
    residual_reduction: str = "sum"  # "sum" (paper) or "mean" (per-element-mean of ||L_dyn||^2)
    diagnostic_grad_norms: bool = False  # if True, print grad norms of latent/action parameters per inner step
    history_action_pad: str = "zeros"  # "zeros" or "repeat_available" for missing DINO action history
    pad_initial_history: bool = True  # if False, start from available context and let DINO history grow

    lambda_dynamics: float = 1e-4 # weight for dynamics residuals, if included in the objective as a soft penalty (ignored if use_dynamics_constraints is True)
    dynamics_mode: str = "soft" # "rollout" = actions only, latents generated by DINO-WM
                                # "alm" to include dynamics as ALM residuals, "penalty" to include dynamics violation as a soft penalty in the objective, 
                                # "soft" to include dynamics as a soft penalty but without dual variables or ALM updates
                                # "none" to ignore dynamics altogether
    use_dynamics_constraints: bool = True # false to test only feasibility penalty 

    # anti stilness 
    lambda_anti_stillness: float = 0.0
    min_action_norm: float = 0.2

@dataclass
class ActionSearchConfig:
    # existing_alm preserves the original solver behavior.
    method: Literal[
        "existing_alm",
        "multistart_adam",
        "langevin_adam",
    ] = "existing_alm"

    # Number of independent initial action trajectories.
    num_starts: int = 8

    # Standard deviation of perturbations around the base/warm start.
    initialization_noise_std: float = 0.3

    # Include the unchanged base/warm-start trajectory as chain zero.
    include_base: bool = True

    # Reproducibility for initialization and Langevin noise.
    seed: int = 0

    # Prevent raw parameters from saturating the tanh action transform.
    raw_action_limit: float | None = 3.0

    multistart_adam: MultiStartAdamConfig = field(
        default_factory=MultiStartAdamConfig
    )

    langevin_adam: LangevinAdamConfig = field(
        default_factory=LangevinAdamConfig
    )

    def __post_init__(self) -> None:
        valid_methods = {
            "existing_alm",
            "multistart_adam",
            "langevin_adam",
        }

        if self.method not in valid_methods:
            raise ValueError(
                f"Unknown action-search method {self.method!r}; "
                f"expected one of {sorted(valid_methods)}."
            )

        if self.num_starts < 1:
            raise ValueError("num_starts must be at least 1.")

        if self.initialization_noise_std < 0:
            raise ValueError(
                "initialization_noise_std must be non-negative."
            )

        if (
            self.raw_action_limit is not None
            and self.raw_action_limit <= 0
        ):
            raise ValueError(
                "raw_action_limit must be positive or None."
            )


@dataclass
class LangevinActionConfig:
    enabled: bool = False
    num_steps: int = 20 # probably has no effect 
    step_size: float = 1e-2
    temperature: float = 1e-5
    num_restarts: int = 1 # could be removed? 
    restart_noise_std: float = 0.2
    grad_clip_norm: Optional[float] = 10.0
    add_noise: bool = True

@dataclass
class RefinementConfig:
    enabled: bool = True
    num_samples: int = 500
    noise_variance: float = 0.3
    objective: str = "goal"  # "goal" (paper text) or "planner" (video+goal+action)


@dataclass
class MPCConfig:
    horizon: int = 25
    execution_stride: int = 1
    warm_start: bool = False 


@dataclass
class PlannerConfig:
    alm: ALMConfig = field(default_factory=ALMConfig)
    mpc: MPCConfig = field(default_factory=MPCConfig)
    refinement: RefinementConfig = field(default_factory=RefinementConfig)
    feasibility: FeasibilityConfig = field(default_factory=FeasibilityConfig)
    langevin_action: LangevinActionConfig = field(default_factory=LangevinActionConfig)
    action_search: ActionSearchConfig = field(default_factory=ActionSearchConfig)
